name: Upload to GCR and deploy

on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker to use GCR
        run: |
          gcloud auth configure-docker gcr.io

      - name: Build and tag Docker image
        run: |
          docker build -t gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} .
          docker tag gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.IMAGE_NAME }}:latest

      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.IMAGE_NAME }}:latest
      - name: Deploy to Cloud Run

        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_PWD: ${{ secrets.DB_PWD }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          KC_ADMIN_PASSWORD: ${{ secrets.KC_ADMIN_PASSWORD }}
          KC_ADMIN_USERNAME: ${{ secrets.KC_ADMIN_USERNAME }}
          KC_CLIENT: ${{ secrets.KC_CLIENT }}
          KC_REALM: ${{ secrets.KC_REALM }}
          KC_URL: ${{ secrets.KC_URL }}
          MS_PORT: ${{ secrets.MS_PORT }}

          AMAZON_AWS_ACCESS_KEY: ${{ secrets.AMAZON_AWS_ACCESS_KEY }}
          AMAZON_AWS_REGION: ${{ secrets.AMAZON_AWS_REGION }}
          AMAZON_AWS_SECRET_KEY: ${{ secrets.AMAZON_AWS_SECRET_KEY }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          REGION: ${{ secrets.REGION }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}






        run: |
          gcloud run deploy ${{ secrets.SERVICE_NAME }} \
            --image gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} \
            --platform managed \
            --region ${{ secrets.REGION }} \
            --port 8004 \
            --allow-unauthenticated \
            --set-env-vars "dbName=$DB_NAME, dbPort=$DB_PORT, dbPwd=$DB_PWD, dbUrl=$DB_URL, dbUser=$DB_USER, kcAdminPassword=$KC_ADMIN_PASSWORD, kcAdminUsername=$KC_ADMIN_USERNAME, kcClient=$KC_CLIENT, kcRealm=$KC_REALM, kcUrl=$KC_URL, msPort=$MS_PORT,amazonAwsAccessKey=$AMAZON_AWS_ACCESS_KEY,amazonAwsRegion=$AMAZON_AWS_REGION, amazonAwsSecretKey=$AMAZON_AWS_SECRET_KEY"
